# Generated by Django 4.2.27 on 2025-12-31 16:57

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('payer_email', models.EmailField(max_length=254)),
                ('purpose', models.CharField(choices=[('ENTRY_FEE', 'Entry Fee'), ('FINAL_CHARGE', 'Final Charge')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='SAR', max_length=3)),
                ('tap_charge_id', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(choices=[('INITIATED', 'Initiated'), ('CAPTURED', 'Captured'), ('FAILED', 'Failed'), ('UNKNOWN', 'Unknown')], default='INITIATED', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('auction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portfolio.mazaady')),
            ],
        ),
        migrations.CreateModel(
            name='AuctionEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payer_email', models.EmailField(max_length=254)),
                ('is_paid', models.BooleanField(default=False)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('auction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portfolio.mazaady')),
            ],
            options={
                'unique_together': {('auction', 'payer_email')},
            },
        ),
    ]
