# Generated by Django 4.2.27 on 2026-01-07 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0007_bid_favorite'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='bidding_access',
            field=models.BooleanField(default=False),
        ),
    ]
