# Generated by Django 6.0 on 2026-01-07 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0007_bid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='status',
            field=models.CharField(choices=[('IN_REVIEW', 'In Review'), ('ACTIVE', 'Active'), ('REJECTED', 'Rejected')], default='ACTIVE', max_length=20),
        ),
    ]
