# Generated by Django 4.2.27 on 2026-01-07 13:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0008_profile_bidding_access'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='auction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='portfolio.mazaady'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='purpose',
            field=models.CharField(choices=[('ENTRY_FEE', 'Entry Fee'), ('FINAL_CHARGE', 'Final Charge'), ('GLOBAL_ACCESS', 'Global Bidding Access')], max_length=20),
        ),
    ]
