# Generated by Django 4.2.27 on 2026-01-07 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0009_alter_payment_auction_alter_payment_purpose'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='masked_id',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
