# Generated by Django 6.0 on 2026-01-08 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0009_car_winner_alter_car_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='start_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='car',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('IN_REVIEW', 'In Review'), ('ACTIVE', 'Active'), ('REJECTED', 'Rejected'), ('CLOSED', 'Closed')], default='ACTIVE', max_length=20),
        ),
    ]
