# Generated by Django 4.2.27 on 2026-01-09 20:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0010_profile_bidding_access_profile_masked_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='car',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='portfolio.car'),
        ),
    ]
