# Generated by Django 6.0 on 2026-01-12 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0011_alter_car_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('IN_REVIEW', 'In Review'), ('SOON', 'Soon'), ('ACTIVE', 'Active'), ('REJECTED', 'Rejected'), ('CLOSED', 'Closed')], default='IN_REVIEW', max_length=20),
        ),
    ]
