# Generated by Django 4.2.27 on 2026-01-10 21:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('portfolio', '0013_alter_profile_rating'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('OUTBID', 'تم تجاوز عرضك'), ('AUCTION_ENDING', 'المزاد ينتهي قريباً'), ('AUCTION_WON', 'فزت بالمزاد'), ('NEW_BID', 'عرض جديد على سيارتك'), ('AUCTION_ENDED', 'انتهى المزاد'), ('PAYMENT_CONFIRMED', 'تم تأكيد الدفع'), ('SYSTEM', 'إشعار النظام')], max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('link', models.CharField(blank=True, max_length=200, null=True)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
