# Generated by Django 4.2.27 on 2026-01-12 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0012_alter_car_status'),
        ('portfolio', '0014_notification'),
    ]

    operations = [
    ]
