# Generated by Django 6.0 on 2026-01-12 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0012_alter_car_status'),
        ('portfolio', '0014_notification'),
    ]

    operations = [
    ]
