# Generated by Django 6.0 on 2026-01-15 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0015_merge_0012_alter_car_status_0014_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='body_type',
            field=models.CharField(default='Sedan', max_length=50),
        ),
    ]
