# Generated by Django 4.2.27 on 2026-01-14 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0015_merge_0012_alter_car_status_0014_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='status',
            field=models.CharField(choices=[('IN_REVIEW', 'In Review'), ('SOON', 'Soon'), ('ACTIVE', 'Active'), ('REJECTED', 'Rejected'), ('CLOSED', 'Closed')], default='IN_REVIEW', max_length=20),
        ),
    ]
