# Generated by Django 6.0 on 2026-01-21 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0016_car_body_type'),
        ('portfolio', '0016_remove_pending_status'),
    ]

    operations = [
    ]
