# Generated by Django 4.2.27 on 2026-01-17 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0016_car_body_type'),
        ('portfolio', '0016_remove_pending_status'),
    ]

    operations = [
    ]
