# Generated by Django 4.2.27 on 2026-01-21 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0018_profile_wallet_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='closed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
