# Generated by Django 4.2.27 on 2026-01-21 19:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0019_car_closed_at'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AuctionEntry',
        ),
    ]
