# Generated by Django 4.2.27 on 2026-01-21 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0020_delete_auctionentry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='purpose',
            field=models.CharField(choices=[('FINAL_CHARGE', 'Final Charge'), ('BIDDING_ACCESS', 'Bidding Access')], max_length=20),
        ),
    ]
