# Generated by Django 6.0 on 2026-01-24 18:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0021_alter_payment_purpose'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='closed_at',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='wallet_balance',
        ),
        migrations.AlterField(
            model_name='payment',
            name='purpose',
            field=models.CharField(choices=[('ENTRY_FEE', 'Entry Fee'), ('FINAL_CHARGE', 'Final Charge'), ('BIDDING_ACCESS', 'Bidding Access')], max_length=20),
        ),
        migrations.CreateModel(
            name='AuctionEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_paid', models.BooleanField(default=False)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('auction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portfolio.mazaady')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('auction', 'user')},
            },
        ),
    ]
