# Generated by Django 4.2.27 on 2026-01-24 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0023_profile_wallet_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='closed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='purpose',
            field=models.CharField(choices=[('FINAL_CHARGE', 'Final Charge'), ('BIDDING_ACCESS', 'Bidding Access')], max_length=20),
        ),
        migrations.DeleteModel(
            name='AuctionEntry',
        ),
    ]
